import UserHeader from "../../components/shared/header/UserHeader";
import { UserNavBar } from "../../components/navbars/UserNavbar"

export const metadata = {
    title: "Tibb-Jox",
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <div>
        <UserHeader/>
        <UserNavBar />
        {children}
      </div>
    )
  }