import UserPageLayout from "../../components/shared/userpage/user-layout";
import Link from "next/link";
import { FavoriteIcon, HomeIcon, OrdersIcon, SettingsIcon } from '../../components/icons/Icons'

export const metadata = {
    title: "Tibb-Jox",
    description: 'Generated by Next.js',
  }
  
  export default function UserDashboardLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    const links = [
      {
        title: 'Profile',
        href: '/user/profile',
        icon: <HomeIcon/>
      },
      {
        title: 'Orders',
        href: '/user/orders',
        icon: <OrdersIcon/>
      },
      {
        title: 'Favorites',
        href: '/user/favorites',
        icon: <FavoriteIcon/>
      },
      {
        title: 'Settings',
        href: '/user/settings',
        icon: <SettingsIcon/>
      },
    ]

    return (
      <UserPageLayout links={links}>
        {children}
      </UserPageLayout>
    )
  }